apiVersion: apps/v1
kind: Deployment
metadata:
  name: minigo-matchmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minigo-matchmaker
  template:
    metadata:
      labels:
        app: tminigo-matchmakerpu-player
    spec:
      containers:
      - name: minigo-matchmaker
        image: gcr.io/tensor-go/minigo-matchmaker:v0
        imagePullPolicy: Always
        volumeMounts:
        - name: service-credentials
          mountPath: /etc/credentials
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/credentials/service-account.json
        - name: MODEL_BUCKET
          value: $MODEL_BUCKET
        - name: SGF_BUCKET
          value: $SGF_BUCKET
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: cloudsql-proxy
					image: gcr.io/cloudsql-docker/gce-proxy:1.11
					command: ["/cloud_sql_proxy",
										"-instances=<INSTANCE_CONNECTION_NAME>=tcp:3306", # TODO
										"-credential_file=/secrets/cloudsql/credentials.json"]
					securityContext:
						runAsUser: 2  # non-root user
						allowPrivilegeEscalation: false
					volumeMounts:
						- name: cloudsql-instance-credentials
							mountPath: /secrets/cloudsql
							readOnly: true

      volumes:
      - name: service-credentials
        secret:
          secretName: $SERVICE_ACCOUNT-creds
			- name: cloudsql-instance-credentials
				secret:
          secretName: cloudsql-instance-credentials
      restartPolicy: Always
